name: Deploy Website

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # If your build artifacts need to be created:
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        run: |
          cd /home/ec2-user/awsiq/fallstreak-website
          # Pull the latest changes from your repository
          git pull origin main
          # Install any new dependencies
          npm install
          # Optional: build if your project needs it
          npm run build
          # Restart the service so changes take effect
          sudo systemctl restart reactapp.service
