name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to website
        run: |
          set -ex
          echo "Changing directory to /home/awsiq/fallstreak-website"
          cd /home/awsiq/fallstreak-website
          echo "Current directory: $(pwd)"
          ls -la
          echo "Pulling latest code"
          git pull origin main
          echo "Installing dependencies"
          npm install
          echo "Building project"
          npm run build
          echo "Restarting service"
          sudo systemctl restart reactapp.service
