name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ec2-runner]

    steps:
      # Clone your repository on the runner.
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Node.js environment.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies for the main website.
      - name: Install main website dependencies
        run: |
          cd fallstreak-website
          npm ci

      # Install dependencies for the backend.
      - name: Install backend dependencies
        run: |
          cd fallstreak-website/contact-form-backend
          npm ci

      # Build the React app.
      - name: Build main website
        run: |
          cd fallstreak-website
          npm run build

      # Restart the systemd service for your React app.
      - name: Restart reactapp-service
        run: sudo systemctl restart reactapp-service

      # Restart the contact form backend.
      - name: Restart contact form backend server
        run: |
          cd fallstreak-website/contact-form-backend
          # Terminate any running instance of server.jsx, ignoring errors if not running.
          pkill -f server.jsx || true
          sleep 2
          # Restart server.jsx in the background.
          nohup node server.jsx > server.log 2>&1 &
