name: Deploy Website

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync repository to website root
        run: |
          echo "Syncing repository to /home/ec2-user/awsiq/fallstreak-website"
          rsync -av --delete "$GITHUB_WORKSPACE/" "/home/ec2-user/awsiq/fallstreak-website/"

      - name: Deploy to website
        run: |
          set -ex
          # Change to the website's root directory
          cd /home/ec2-user/awsiq/fallstreak-website
          echo "Current directory: $(pwd)"
          ls -la
          # Install dependencies and build the project
          echo "Installing dependencies"
          npm install
          echo "Building project"
          npm run build
          # Restart the service to apply the new changes
          echo "Restarting service"
          sudo systemctl restart reactapp.service
